baseurl: ''
exclude: ['README.md']
permalink: pretty
title: "Leah Exotic's 2021"


google_analytics_id: ""
homepage:
  show_call_box: true
# logo:
#   mobile: "images/logo/logo-mobile.svg"
#   desktop: "images/logo/logo.svg"
#   desktop_height: "36px"
footer:
  copyright_text: 'Leah Exotic LLC'

seo:
  meta_og_title: "Leah Exotic's 2021"
  meta_og_type: "website"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: ""
  meta_twitter_card: "summary"
  meta_twitter_site: "@jablowinmymind"
  meta_twitter_creator: "@jablowinmymind"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10
  sass_dir: ./_sass

plugins:
  - jekyll-environment-variables
